# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/arkency-command_bus/all/arkency-command_bus.rbi
#
# arkency-command_bus-0.4.0

module Arkency
end
class Arkency::CommandBus
  def call(command); end
  def handlers; end
  def initialize; end
  def register(klass, handler); end
end
class Arkency::CommandBus::UnregisteredHandler < StandardError
end
class Arkency::CommandBus::MultipleHandlers < StandardError
end
