# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_35; end
module ::Anonymous_Delegator_55; end
module ::Anonymous_Delegator_56; end
module ::Anonymous_Delegator_61; end
module ::Anonymous_Delegator_7; end
module ActionDispatch::Response::ContentTypeHeader; end
module ActiveRecord::Associations::Association; end
module Rails::Engine::Configuration; end
